development:
  adapter: postgresql
  database: crawl_the_bar_dev
  username: stuwagsmac
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: crawl_the_bar_test
  username: stuwagsmac
  password:
  pool: 5
  timeout: 5000